title: Harsh Trivedi
logo: assets/img/avatar-g27a5da72b_1280.png
description: Portfolio
show_downloads: true
 <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>

google_analytics:
theme: jekyll-theme-minimal
