title: Harsh Trivedi
logo: assets/img/avatar-g27a5da72b_1280.png
description: 
  <p align="center">Portfolio
  <br>   
  I'm working on Data Science,Machine learning & NLP related problems.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
